### PR TITLE
Create StaySphere.Infrastructure

### PR DESCRIPTION
**Pull request by Nabiddinov**

### CODE REVIEW

**Review by SharifovDeveloper — DISMISSED** [review]
Looks good

**Review by diyorzz — DISMISSED** [review]
Great!

**Review by SharifovDeveloper — DISMISSED** [review]
Looks good

**Comment by Nabiddinov** [comment]
good

**Review by SharifovDeveloper — APPROVED** [review]
Looks good

**Review by SharifovDeveloper — APPROVED** [review]
Looks good

**Review by diyorzz — APPROVED** [review]

**Pull request closed without merging**
